[package]
name = "gen_elf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"
object = { version = "0.36.5", features = ["write_core"] }
